### ISSUE TITLE
kind2string custom converters

### ISSUE THREAD

**Issue by chasestarr** [atlassian/extract-react-types#100]
Hi there, I'm working on a simple type renderer like `pretty-proptypes` and have been digging through the `kind2string` package. Essentially, I am looking to render something close vscode's type inspector where if a `referenceIdName` exists, we render that instead of expanding the type.

<img width="383" alt="Screen Shot 2019-10-23 at 9 23 34 AM" src="https://user-images.githubusercontent.com/5317799/67428040-35505c00-f592-11e9-8724-b9e86305498f.png">

The package's readme says
> It also exposes its converter object, allowing you to overwrite converters of your choice, if you wish to perform some other action other than the default string converter.

But it looks like the `converters` are not exported. Do we mind if I send a PR to do so? Right now, my solution is to vendor all of the source code into my project.

**Comment by Noviny** [comment]
Hi @chasestarr, this looks like a good idea to me. I think the docs are referencing `Components` being exported, but I don't think that's enough for your use-case.

Add me as a reviewer when you get your PR up.
