### ISSUE TITLE
Add converter for TSTypeQuery

### ISSUE THREAD

**Issue by etlovett** [atlassian/extract-react-types#113]
I have a React component with a prop with the Typescript type `ComponentProps<typeof OtherComponent>['type']`, where `OtherComponent`'s `type` prop is a union of string constants (e.g. `type: 'a' | 'b' | 'c'`).  When I run this component through `extract-react-types-loader` (via `require('!!extract-react-types-loader!./MyComponent.tsx')`), I get the error `Missing converter for: TSTypeQuery`.  

Per https://astexplorer.net/#/gist/1c8639f2528c0a3abeffeb6f5b06d074/0e1bfbd296ea053ce20a6829baacb858797fca90, I believe it's the `typeof` that produces a `TSTypeQuery` AST node.

FYI, I believe this issue is just a `TSTypeQuery` version of https://github.com/atlassian/extract-react-types/issues/59 and https://github.com/atlassian/extract-react-types/issues/75.

Thanks for a handy tool!

**Comment by danieldelcore** [comment]
Hey @etlovett 👋 

Currently there's no support for `TSTypeQuery` but we're keen to include it! 
It would be a matter of just adding a new converter, `converter.TSTypeQuery`. 

Not sure when we'll be able to get around to adding this, but you're more than welcome to give it a go if you're interested in contributing 😃 

Cheers!
