### ISSUE TITLE
Add support for FC<Props>

### ISSUE THREAD

**Issue by danieldelcore** [atlassian/extract-react-types#136]
Components typed using FC from `@types/react` should be supported.

**Comment by elisechant** [comment]
Confirming this is an issue, and a priority to fix. 

For: 
```
<Props
  props={require('!!extract-react-types-loader!../src/my-component')}
/>
```

/src/my-component
Works:
```
import React from 'react';
interface Props {
  title: string;
}
export default ({
  title,
}: Props) => (
  <p>Hello</p>
)
```

Does not work, **but should**: 
interface Props {
  title: string;
}
const EmptyState: React.FC<Props> = ({
  title,
}) => (
  <p>Hello</p>
);
export default EmptyState;

**Comment by elisechant** [comment]
This can be worked around for the time being, by adding an addition file: 

./src/my-component/index.tsx
```
#export interface Props {
  title: string;
}
const EmptyState: React.FC<Props> = ({
  title,
}) => (
  <p>Hello</p>
);
export default EmptyState;
```

./src/my-component/_atlaskit-docs-props.tsx
```
import { Props } from './my-component';
export default (arg: Props) => null
```

And importing this file instead, ie
```
<Props
  props={require('!!extract-react-types-loader!../src/my-component/_atlaskit-docs-props')}
/>
```
