### ISSUE TITLE
Decouple from atlaskit website build

### ISSUE THREAD

**Issue by marionebl** [atlassian/extract-react-types#195]
The webpack loader depends directly on env variables specific to the atlaskit website build environment. Remove the direct access and expose config keys instead

https://github.com/atlassian/extract-react-types/blob/master/packages/extract-react-types-loader/index.js#L38-L39

----
Alternatively we could in-source the loader, what's your take @danieldelcore ?

**Comment by marionebl** [comment]
Alternatively we could in-source the loader, what's your take @danieldelcore ?

**Comment by danieldelcore** [comment]
Hey @marionebl 👋 

> Remove the direct access and expose config keys instead

Can you elaborate on this a bit? I'm not sure I understand 🤔 

I agree that this condition could probably be moved out of this repo and toggled on/off however the user requires. 

```js
!['staging', 'production'].includes(process.env.WEBSITE_ENV) && !process.env.FORCE_EXTRACT_REACT_TYPES
```

Is there a nice way to do this in webpack? I guess by providing different configs for different environments 🤔

**Comment by marionebl** [comment]
> Is there a nice way to do this in webpack? I guess by providing different configs for different environments 🤔

Our own usage is mostly inline-loader requires, e.g. 

```ts
require('!!extract-react-types!./Button.tsx');
```

Unfortunately there is no straightforward to have user-configurable defaults for those - the conventional way to pass options in is query parameter 😬 

```
require('!!extract-react-types?a=b!./Button.tsx');
```

In our case we could use the `resolveLoader` config to alias `extract-react-types-loader` to the noop branch, e.g.

```ts
    resolveLoader: {
      alias: opts.extractReactTypes ? undefined : {
        'extract-react-types-loader': require.resolve('./noop-extract-react-types-loader'),
      },
    },
```

The npm module could make this slightly nicer by providing a `noop` entry point:

```ts
    resolveLoader: {
      alias: opts.extractReactTypes ? undefined : {
        'extract-react-types-loader': require.resolve('extract-react-types-loader/noop'),
      },
    },
```
