### ISSUE TITLE
Avoid including `ts-ignore` and `eslint-disable-next-line` in docs

### ISSUE THREAD

**Issue by danieldelcore** [atlassian/extract-react-types#198]
In this case, the eslint-disable will be included in the actual docs of the component. We need to define a way to omit these comments

```tsx
interface Props {
  // eslint-disable-next-line @repo/internal/react/consistent-props-definitions
  /** This is my prop doc */
  bar: 'Foo';
}
```

**Comment by madou** [comment]
Thanks for raising! I was looking through source and found: https://github.com/atlassian/extract-react-types/blob/47978d90a9c45c57cbd719d9731fb869d56376a3/packages/pretty-proptypes/src/PropType/index.js#L31

If we filter out comments (and only use multi line comments) it could be a starting point? Is there any use case to include single line comments?
