### ISSUE TITLE
Add ability to hide selected fields

### ISSUE THREAD

**Issue by intarabang** [atlassian/extract-react-types#38]
We have a use case where the component whose props we want to expose is wrapped by a HOC to inject analytics. The types that ended up loaded are the union of the base and analytics props but we want to keep the latter internal.
We have a workaround now but it's not ideal. It'd be great if we'd be able to hide certain fields from being loaded so we can display this for documentation. The solution might make more sense to come from extract-react-types-loader but I was unable to find where to submit an issue there.

**Comment by Noviny** [comment]
`extract-react-types-loader` is a bit hidden atm, it's in the atlaskit repo on bitbucket, though we are thinking of bringing it here as of #39.

As to solving your problem, there are 2 ways to do this already, which hopefully solve the problem for you.

1. You can separate the files where the unwrapped and wrapped components live, and point extract-react-types at the unwrapped component only. This is very effective BUT does change how you write your source, which is not hugely transparent.

2. [pretty-proptypes](https://github.com/Noviny/pretty-proptypes#overrides) has an option to override. If you're using `pretty-proptypes` to render your types, you could have an override that looked like:

```
${<Props
  props={require('!!extract-react-types-loader!../../PropTypes/Select')}
  overrides={{
    unwantedProp1: () => null,
    unwantedProp2: () => null,
}}
/>}
```

This solution stays away from changing your source code, while still hiding the selected props.

Let me know if these solutions work for you, or if there are other problems that need addressing.

**Comment by intarabang** [comment]
Thanks, Ben. I'm using pretty-proptypes so the second solution worked perfectly. Cheers!
