### ISSUE TITLE
Decorator support + Missing defaults

### ISSUE THREAD

**Issue by bebraw** [atlassian/extract-react-types#53]
Thanks for the extraction utilities. They are highly useful.

While benchmarking `extract-react-types`, I noticed a couple of issues:

* Decorators were disabled (Babel 7 change)?
* `addDefaultProps` could crash. If you want, I can figure out a test case for this.

Here are my initial fixes: https://github.com/bebraw/extract-react-types/commit/42fbdb625b447ea42a68e38fea7b6707441e8a56 . I can also PR if you want.

**Comment by Noviny** [comment]
PR with test cases would be fantastic, thankyou!

**Comment by bebraw** [comment]
Ok, PR'd.

**Comment by bebraw** [comment]
Do you have ETA for a release? Just curious.

**Comment by Noviny** [comment]
Sorry, just published today. Wanted to get one other small change in as well.

**Comment by bebraw** [comment]
No worries. Thanks a lot!
